
package modelo.vistas;

import javax.swing.JToggleButton;

/**
 *
 * @author Brandon Ortiz
 */

public class visiorOpcionesProfesor extends javax.swing.JFrame {

   
    public visiorOpcionesProfesor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCursos = new javax.swing.JButton();
        btnInscripciones = new javax.swing.JButton();
        botonLoggin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAdministradorUsuarios = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCursos.setBackground(new java.awt.Color(153, 255, 255));
        btnCursos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCursos.setText("Cursos");
        btnCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursosActionPerformed(evt);
            }
        });

        btnInscripciones.setBackground(new java.awt.Color(255, 51, 255));
        btnInscripciones.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnInscripciones.setText("Inscripciones");
        btnInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscripcionesActionPerformed(evt);
            }
        });

        botonLoggin.setBackground(new java.awt.Color(255, 204, 204));
        botonLoggin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botonLoggin.setText("Regresar al inicio");
        botonLoggin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLogginActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("¿A cual desea ingresar?");

        btnAdministradorUsuarios.setBackground(new java.awt.Color(102, 255, 102));
        btnAdministradorUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdministradorUsuarios.setText("Administrador de Usuarios");
        btnAdministradorUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministradorUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAdministradorUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonLoggin, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAdministradorUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCursos, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonLoggin, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(171, 171, 171))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursosActionPerformed
                            //metodo para redirigir a la pantalla de cursos
                                 //visorOpcionesProfesor----------->visorCursos
       
    }//GEN-LAST:event_btnCursosActionPerformed

    private void btnInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscripcionesActionPerformed
        // Metodo para redirigir a la pantalla de inscripcion
        //visorOpcionesProfesor----------->visorTablaInscripcion
    }//GEN-LAST:event_btnInscripcionesActionPerformed

    private void botonLogginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLogginActionPerformed
        //Metodo para redirigir a la pantalla del loggin
        //visorOpcionesProfesor---------->visorLoggin
    }//GEN-LAST:event_botonLogginActionPerformed

    private void btnAdministradorUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministradorUsuariosActionPerformed
        // Boton para redirigir al administrador de usuarios
        //----------------------visorCreacionUsuarios
    }//GEN-LAST:event_btnAdministradorUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(visiorOpcionesProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(visiorOpcionesProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(visiorOpcionesProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(visiorOpcionesProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new visiorOpcionesProfesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonLoggin;
    private javax.swing.JToggleButton btnAdministradorUsuarios;
    private javax.swing.JButton btnCursos;
    private javax.swing.JButton btnInscripciones;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
  // se crea getts por que son privados y se ocupan en el controlador
    public javax.swing.JButton getbtnInscripciones() {
    return btnInscripciones;
}

public JToggleButton getbtnAdministradorUsuarios() {
    return btnAdministradorUsuarios;
}

public javax.swing.JButton getbtnCursos(){
    return  btnCursos;
}
}
