
package modelo.vistas;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Brandon Ortiz
 * Esta jframe es para la impresion de la informacion de una tabla en la base de datos, creacion de datos, edicion de datos o Eliminacion de datos
 */
public class visorCursos extends javax.swing.JFrame {

    private int cadenaCursos=0;    
    
    public visorCursos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonRegresoMenu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idCurso = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nombreCurso = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        descripcionCurso = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        idProfesor = new javax.swing.JTextField();
        botonCreacionCurso = new javax.swing.JButton();
        botonEliminarCurso = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCursos = new javax.swing.JTable();
        botonVerTabla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonRegresoMenu.setBackground(new java.awt.Color(153, 204, 255));
        botonRegresoMenu.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        botonRegresoMenu.setForeground(new java.awt.Color(0, 0, 0));
        botonRegresoMenu.setText("Regresar al menu");
        botonRegresoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresoMenuActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel2.setText("Tabla de cursos");

        jLabel3.setText("ID del curso");

        idCurso.setText("46321*");

        jLabel4.setText("Nombre de curso");

        nombreCurso.setText("Catalan 5*");

        jLabel5.setText("Descripcion de la clase");

        descripcionCurso.setText("en esta clase se realisan visionado de un idioma muerto que se estaba tomando durante un birreninato de un incestuoso");

        jLabel6.setText("ID del profesor");

        idProfesor.setText("34736*");

        botonCreacionCurso.setText("crear ");
        botonCreacionCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCreacionCursoActionPerformed(evt);
            }
        });

        botonEliminarCurso.setBackground(new java.awt.Color(255, 51, 51));
        botonEliminarCurso.setForeground(new java.awt.Color(255, 255, 255));
        botonEliminarCurso.setText("Eliminar");
        botonEliminarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarCursoActionPerformed(evt);
            }
        });

        botonEditar.setText("Editar");
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        tablaCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"español", "452352", "443543", "gdfsagdfgfsjsf"}
            },
            new String [] {
                "Curso", "ID", "ID profesor", "Descripcion"
            }
        ));
        tablaCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCursosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCursos);

        botonVerTabla.setText("Visualizar");
        botonVerTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerTablaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonCreacionCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonEliminarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(descripcionCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonRegresoMenu)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVerTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVerTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descripcionCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonCreacionCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonEliminarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonRegresoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 64, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCreacionCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCreacionCursoActionPerformed
        // Boton para agregar a la base de datos la linea con los datos del nuevo curso
        //variables de uso unico para la operacion del if de comprobacion de espacios vacios
        String nombreCurso2=nombreCurso.getText();
        String idCurso2=idCurso.getText();
        String idProfesor2=idProfesor.getText();
        String descripcionCurso2=descripcionCurso.getText();
        
        //instacion del defaultablemodel para poder agregar a la jtabla la informacion agregada
         DefaultTableModel tablon = (DefaultTableModel)tablaCursos.getModel();
         
         if(cadenaCursos==1){//Si no se ha desplegado la tabla de datos No se podra usar el boton de agregar usuario
             
         try{
             
            if(nombreCurso2.equals("")||idCurso2.equals("")||idProfesor2.equals("")||descripcionCurso2.equals("")){
         //en caso de uno de los 5 espacios esta ausente no se procedera la operacion
             JOptionPane.showMessageDialog(this,"No se puede agregar un curso con informacion incompleta");
         }else{//si ningun dato esta vacio:
          //addRow: agregar la informacion como una linea a la tabla del jframe   
         tablon.addRow(new Object[]{nombreCurso.getText(),idCurso.getText(),idProfesor.getText(),descripcionCurso.getText()});
        ///////Procedimientos para agregar a la base de datos el nuevo usuario
        
        ////////////////////
         JOptionPane.showMessageDialog(this,"Se ha agregado el curso");
        //Se informa del exito para conformidad del usuario
        //Se limpian los espacion para evitar un error de duplicado de informacion sin consentimiento
         nombreCurso.setText("");
         idCurso.setText("");
          idProfesor.setText("" );
           descripcionCurso.setText("");
         } 
         
           }catch(Exception ex)
         {
            JOptionPane.showMessageDialog(this,"No se ha logrado Agregar el curso a la base");
             } 
         }//corchete del if
         
    }//GEN-LAST:event_botonCreacionCursoActionPerformed

    private void botonEliminarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarCursoActionPerformed
        // Boton para Eliminar un usuario
        //no habra validacion de espacios vacios porque no se pueden agregar lineas con espacios "vacios" en si
         //selectrowindex es usado para manipular que linea el usuario escoja 
             int selectedRowIndex = tablaCursos.getSelectedRow(); 
        //instacion del defaultablemodel para poder hacer manipulacion en la jtabla
        DefaultTableModel tablon = (DefaultTableModel)tablaCursos.getModel();
        
        if(cadenaCursos==1){//Si no se ha desplegado la tabla de datos No se podra usar el boton de agregar usuario
            
        try{//para evitar problemas usaremos un try catch
             //el codigo por si solo puede "funcionar" pero genera alertas rojas por tocar una linea en la tabla, una por una
             //con un try catch evitamos la acumulacion de alertas al punto de congelar la funcion de tocar una linea
             
             ////////Espacio para realisar los procedimientos para eliminar los datos en la base de datos
             
             //////////////////////////////////////////////////////////////////////////////////////////
              tablon.removeRow(selectedRowIndex);//linea para eliminar la tabla seleccionada
             
        
         }catch(Exception ex)
         {
            JOptionPane.showMessageDialog(this,"No se ha logrado eliminar el curso, intente denuevo");
             }
        }//corchete del if
 
        
        if (cadenaCursos==1){///If cerrado por una variable int
            //si los procesos de eliminacion de usuario fueron hechos correctamente se elimina de la jtable
          //Se limpian los espacios para nuevas operaciones despues de informar la accion,
              JOptionPane.showMessageDialog(this,"Se ha Eliminado el curso");
             //en caso de presionar erroneamente Eliminar  se da la ventana de tiempo de ver los datos que borro para apuntarlos y volver a agregarlo
             nombreCurso.setText("");
             idCurso.setText("");
             idProfesor.setText("" );
             descripcionCurso.setText("");  
   
        }else{
        JOptionPane.showMessageDialog(this,"No se puede usar esta funcion hasta activar la tabla");
        }
        
  
    }//GEN-LAST:event_botonEliminarCursoActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        // Boton para editar el cambio en los datos de una linea
       
        //instacion del defaultablemodel para poder hacer manipulacion en la jtabla
        DefaultTableModel tablon = (DefaultTableModel)tablaCursos.getModel();
         //selectrowindex es usado para manipular que linea el usuario escoja 
        int linea = tablaCursos.getSelectedRow(); 
             
        if(cadenaCursos==1){//Si no se ha desplegado la tabla de datos No se podra usar el boton de agregar usuario
            
            
        try{//para evitar problemas usaremos un try catch
             //el codigo por si solo puede "funcionar" pero genera alertas rojas por tocar una linea en la tabla, una por una
             //con un try catch evitamos la acumulacion de alertas al punto de congelar la funcion de tocar una linea
              if (linea>=0){//cualquier linea esta siendo tocada
             ///Espacio para realisar los procesos de base de datos para editar la informacion/////////
             
             //////////////////////////////////////////////////////////////////////////////////////////
            //restablecemos los datos en la linea tocada con la inforacion que se encuentre actualmente en los textfields
             tablon.setValueAt(nombreCurso.getText(),linea,0);   
             tablon.setValueAt(idCurso.getText(),linea,1);   
             tablon.setValueAt(idProfesor.getText(),linea,2);
             tablon.setValueAt(descripcionCurso.getText(),linea,3);
       
           
            }//////corchete de if linea tocada
             
             
         }catch(Exception ex)
         {
             //mensaje para indicar que algo no funciono y exploto 
            JOptionPane.showMessageDialog(this,"No se ha logrado Editar correctamente al usuario");
             }////
        }/////corchete del if
        
         
         
         if (cadenaCursos==1){//si los procesos para editar la linea fueron hechos sin problemas se activara este
            if (linea>=0){///cualquier linea esta siendo tocada
             //restablecemos los datos en la linea tocada con la inforacion que se encuentre actualmente en los textfields  
              tablon.setValueAt(nombreCurso.getText(),linea,0);   
             tablon.setValueAt(idCurso.getText(),linea,1);   
             tablon.setValueAt(idProfesor.getText(),linea,2);
             tablon.setValueAt(descripcionCurso.getText(),linea,3);
             
             nombreCurso.setText("");
             idCurso.setText("");
             idProfesor.setText("" );
             descripcionCurso.setText("" );
             
             JOptionPane.showMessageDialog(this,"Se ha Editado al usuario correctamente");
         }///
         }else{
         JOptionPane.showMessageDialog(this,"No se puede usar esta funcion hasta activar la tabla");
         } 
      
    }//GEN-LAST:event_botonEditarActionPerformed

    private void botonRegresoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresoMenuActionPerformed
        //Boton para regresar a la pantalla de opciones profesor
        //------------------->visiorOpcionesProfesor
        visiorOpcionesProfesor pantalla = new visiorOpcionesProfesor();
        pantalla.setVisible(true);
         dispose();
        setVisible(false);
    }//GEN-LAST:event_botonRegresoMenuActionPerformed

    private void botonVerTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerTablaActionPerformed
        // Boton Para imprimir la informacion en la tabla de contenido
        

        /////////procedimientos para creacion de datos
        try{
        String[] linea1 = {"1", "2", "3","4","5"};
         String[] linea2 = {"1", "2", "3","4","5"};
         String [][]linea={linea1,linea2};
          String []colum={"Curso","ID","ID Profesor","Descripcion"};
           tablaCursos.setModel(new javax.swing.table.DefaultTableModel(linea, colum));
        ////////////
       cadenaCursos=1;//
        JOptionPane.showMessageDialog(this,"Se ha activado la tabla de vizualisacion");//opcional
        //se procura tener los espacios limpios para el usuo del usuario
        nombreCurso.setText("");
         idCurso.setText("");
          idProfesor.setText("" );
           descripcionCurso.setText("" );
        
           }catch(Exception ex)
         {
             //mensaje para indicar que algo no funciono y exploto 
            JOptionPane.showMessageDialog(this,"Algo ha fallado");
             }////
          
    }//GEN-LAST:event_botonVerTablaActionPerformed

    private void tablaCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCursosMouseClicked
       //porcion de codigo para vizualisar en los espacios de textfield la fila seleccionada por un maus del usuario
        //Para mejor experiencia de usuario cuando seleccione una linea se visualise en los textfields para sea claro cual curso es el que editara o eliminara
        DefaultTableModel tablon = (DefaultTableModel)tablaCursos.getModel();
        
       try{//para evitar problemas usaremos un try catch
        int selectedRowIndex = tablaCursos.getSelectedRow();
        //el index es RowIndex es la fila donde se presione y el numero es la guia para cual dato de x columna ira al textfield correspondiente
        nombreCurso.setText(tablon.getValueAt (selectedRowIndex,0).toString());
         idCurso.setText(tablon.getValueAt (selectedRowIndex,1).toString() );
          idProfesor.setText(tablon.getValueAt (selectedRowIndex,2).toString() );
           descripcionCurso.setText(tablon.getValueAt (selectedRowIndex,3).toString() );
           
          
       }catch(Exception ex)
         {
             }
    }//GEN-LAST:event_tablaCursosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(visorCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(visorCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(visorCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(visorCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new visorCursos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCreacionCurso;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonEliminarCurso;
    private javax.swing.JButton botonRegresoMenu;
    private javax.swing.JButton botonVerTabla;
    private javax.swing.JTextField descripcionCurso;
    private javax.swing.JTextField idCurso;
    private javax.swing.JTextField idProfesor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreCurso;
    private javax.swing.JTable tablaCursos;
    // End of variables declaration//GEN-END:variables
}
