
package modelo.vistas;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.Random;

/**
 *
 * @author Brandon Ortiz
 * //estoy considerando si deba heredar los datos de logeo o hacerlo mas simple y que el estudiante deba volver a poner credenciales para visualisar lo suyo
 */
public class visorInformacionEstudiante extends javax.swing.JFrame {

     private String nombre;
     private String contraseña;

     private int contadorCursos;
     private int candadoImpresion;
     private int candadoDeCursos;
    public visorInformacionEstudiante() {
        initComponents();
    }
    
    
    public void pasoDatosLogginEstudiante (String nombre,String contra){
    this.nombre=nombre;
    this.contraseña=contra;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaVisorDeCursosEstudiante = new javax.swing.JTable();
        botonRegresoLoggin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        verNombreEstudiante = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        verContraseñaEstudiante = new javax.swing.JLabel();
        verCorreoEstudiante = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonInformacionEstudiante = new javax.swing.JButton();
        idDelEstudiante = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TablaVisorDeCursosEstudiante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Estudiante", "ID Inscripcion", "ID Curso", "Fecha de registro"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Long.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaVisorDeCursosEstudiante);

        botonRegresoLoggin.setBackground(new java.awt.Color(51, 255, 255));
        botonRegresoLoggin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botonRegresoLoggin.setForeground(new java.awt.Color(0, 0, 0));
        botonRegresoLoggin.setText("Regresar");
        botonRegresoLoggin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresoLogginActionPerformed(evt);
            }
        });

        jLabel1.setText("Informacion del estudiante:");

        verNombreEstudiante.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        verNombreEstudiante.setText(".");

        jLabel3.setText("Correo electronico");

        jLabel4.setText("Contraseña");

        verContraseñaEstudiante.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        verContraseñaEstudiante.setText(".");

        verCorreoEstudiante.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        verCorreoEstudiante.setText(".");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel2.setText("Cursos que dispone el estudiante");

        botonInformacionEstudiante.setText("Cargar informacion estudiante");
        botonInformacionEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInformacionEstudianteActionPerformed(evt);
            }
        });

        idDelEstudiante.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonRegresoLoggin, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(verNombreEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(idDelEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(verContraseñaEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(verCorreoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonInformacionEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idDelEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(verNombreEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                                .addComponent(botonInformacionEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(173, 173, 173))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(verCorreoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(verContraseñaEstudiante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addComponent(botonRegresoLoggin, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresoLogginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresoLogginActionPerformed
        // Boton para regresar al menu de loggeo
        //visorInformacionEstudiante-------->visorLoggin
        visorLoggin pantalla =new visorLoggin();
        pantalla.setVisible(true);
        dispose();
        setVisible(false);
    }//GEN-LAST:event_botonRegresoLogginActionPerformed

    private void botonInformacionEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInformacionEstudianteActionPerformed
        // Boton para imprimir la informacion del estudiante
       
        if(contadorCursos<=4){
          
            try{
         String[][] data = {
            {"1", "Café", "2.50","kge"},
            {"2", "Té", "1.80"},
            {"3", "Jugo", "3.00"},
            {"7","torta","4.60","fgiuwsehiuseui"}
        };
          
  
       String [] colum={"ID estudiante","ID Curso","ID Profesor","Descripcion"}; 
       
        // DefaultTableModel tablon = (DefaultTableModel)prueba.getModel();       
          TablaVisorDeCursosEstudiante.setModel(new javax.swing.table.DefaultTableModel(data, colum));
    
   for (int i=0;i<=data.length;i++){
      if (data [i][1].equals("torta")){
          try{
          JOptionPane.showMessageDialog(this,data[i]);
           String idEstudiante=TablaVisorDeCursosEstudiante.getValueAt(i, 0).toString();
        String IdCurso=TablaVisorDeCursosEstudiante.getValueAt(i, 1).toString();
        String IdProfesor=TablaVisorDeCursosEstudiante.getValueAt(i, 2).toString();
        String descripcion=TablaVisorDeCursosEstudiante.getValueAt(i, 3).toString();
        String []linea = {idEstudiante,IdCurso,IdProfesor,descripcion};
        //tablon.addRow(linea);
        
      }catch(Exception ex)
         {
           JOptionPane.showMessageDialog(this,"hrñlhjrgdkgjrd");
             } 
          
      }
 
} ///////////////////////////////
   
     verNombreEstudiante.setText(nombre);
    verContraseñaEstudiante.setText(contraseña);
        verCorreoEstudiante.setText("judfhjsrhjsrkjdf");
        idDelEstudiante.setText("554433");
        JOptionPane.showMessageDialog(this,"Se ha desplegado la informacion del estudiantes");
         }catch(Exception ex)
         {
           JOptionPane.showMessageDialog(this,"Algo ha fallado gravemente");  
             }   
            
        }else{
        JOptionPane.showMessageDialog(this,"Algo ha fallado gravemente");
        }

       
    }//GEN-LAST:event_botonInformacionEstudianteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(visorInformacionEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(visorInformacionEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(visorInformacionEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(visorInformacionEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new visorInformacionEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaVisorDeCursosEstudiante;
    private javax.swing.JButton botonInformacionEstudiante;
    private javax.swing.JButton botonRegresoLoggin;
    private javax.swing.JLabel idDelEstudiante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel verContraseñaEstudiante;
    private javax.swing.JLabel verCorreoEstudiante;
    private javax.swing.JLabel verNombreEstudiante;
    // End of variables declaration//GEN-END:variables
}
