
package modelo.vistas;
//imports de otras clases
//import modelo.curso;
//imports para operaciones internas
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Brandon Ortiz
 * Esta jframe es para la impresion de la informacion de una tabla en la base de datos, creacion de datos, edicion de datos o Eliminacion de datos
 */
public class visorCreacionUsuario extends javax.swing.JFrame {

    private int cadenaVisualisador=0; // variable para evitar que se agregre o se edite tablas que no existan en la base de datos
    /**
     * Creates new form visorCreacionUsuario
     */
    public visorCreacionUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablavisualizacionUsuarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        RolUsuarioEstudiante = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        verNombreUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        verCorreoUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        verContraseñaUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        verIdUsuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        RolUsuarioProfesor = new javax.swing.JRadioButton();
        botonCrearUsuario = new javax.swing.JButton();
        botonEditarDatosUsuario = new javax.swing.JButton();
        botonEliminarUsuario = new javax.swing.JButton();
        BotonRegresoMenu = new javax.swing.JButton();
        BotonTablaUsuarios = new javax.swing.JButton();
        rolUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablavisualizacionUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"tutu", "214342", "gfGGDFGFDF", "RTREAQG", "patata"}
            },
            new String [] {
                "Nombre", "ID", "Correo", "Contraseña", "Rol"
            }
        ));
        tablavisualizacionUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablavisualizacionUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablavisualizacionUsuarios);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Administrador de usuarios");

        RolUsuarioEstudiante.setText("Estudiante");
        RolUsuarioEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RolUsuarioEstudianteActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre de usuario");

        verNombreUsuario.setText("ricardo maloni");

        jLabel3.setText("Correo electronico");

        verCorreoUsuario.setText("patata437934@gmail.com");

        jLabel4.setText("Contraseña");

        verContraseñaUsuario.setText("987654321");

        jLabel5.setText("Id interno");

        verIdUsuario.setText("7452723");

        jLabel6.setText("Rol");

        RolUsuarioProfesor.setText("Profesor");
        RolUsuarioProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RolUsuarioProfesorActionPerformed(evt);
            }
        });

        botonCrearUsuario.setText("Crear");
        botonCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearUsuarioActionPerformed(evt);
            }
        });

        botonEditarDatosUsuario.setText("Editar");
        botonEditarDatosUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarDatosUsuarioActionPerformed(evt);
            }
        });

        botonEliminarUsuario.setBackground(new java.awt.Color(255, 51, 51));
        botonEliminarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonEliminarUsuario.setForeground(new java.awt.Color(0, 0, 0));
        botonEliminarUsuario.setText("Eliminar");
        botonEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarUsuarioActionPerformed(evt);
            }
        });

        BotonRegresoMenu.setBackground(new java.awt.Color(102, 255, 255));
        BotonRegresoMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BotonRegresoMenu.setForeground(new java.awt.Color(0, 0, 0));
        BotonRegresoMenu.setText("Regresar al menu");
        BotonRegresoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresoMenuActionPerformed(evt);
            }
        });

        BotonTablaUsuarios.setText("Visualizar Informacion");
        BotonTablaUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTablaUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(verNombreUsuario)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(verCorreoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(verContraseñaUsuario)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(verIdUsuario)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(RolUsuarioEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(RolUsuarioProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rolUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BotonRegresoMenu)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonCrearUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEditarDatosUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEliminarUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonTablaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(48, 48, 48)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(verNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(verIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(verCorreoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(verContraseñaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RolUsuarioEstudiante)
                                    .addComponent(RolUsuarioProfesor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rolUsuario))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(botonCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(botonEditarDatosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(147, 147, 147)
                                .addComponent(botonEliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(BotonRegresoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(BotonTablaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RolUsuarioEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RolUsuarioEstudianteActionPerformed
        //radio botom para elejir el rol del usuario
        if (RolUsuarioEstudiante.isSelected()){
        rolUsuario.setText("Estudiante");
        }
    }//GEN-LAST:event_RolUsuarioEstudianteActionPerformed

    private void BotonTablaUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTablaUsuariosActionPerformed
        //Boton para imprimir la informacion en la tabla
         //Para evitar duplicaciones de tablas al inicio de la vizualisacion de la tabla se limpia su contenido para despues imprimirlo el contenido en la base de datos
       //esta linea solo setea los elementos de la columna.
       //tablavisualizacionUsuarios.setModel(new DefaultTableModel(null, new String[]{"Nombre","ID","correo","Contraseña","Rol"})); 
     
        /////////procedimientos para impresion de datos de la base de datos
        try{
         String[] linea1 = {"1", "2", "3","4","5"};
         String[] linea2 = {"1", "2", "3","4","5"};
         String [][]linea={linea1,linea2};
         String []colum={"Nombre", "ID", "Correo","Contraseña","Rol"};
        ///////////////// /////////////
         //Intanciacion del defaulttablemodel para agregar la informacion a la jtabla
        
         tablavisualizacionUsuarios.setModel(new javax.swing.table.DefaultTableModel(linea, colum));
        JOptionPane.showMessageDialog(this,"Se ha activado la Vizualisacion el contenido de la tabla");
        //se procura tener los espacios limpios para el uso del usuario
        cadenaVisualisador=1;
        verNombreUsuario.setText("");
         verIdUsuario.setText("");
          verCorreoUsuario.setText("" );
           verContraseñaUsuario.setText("" );
           rolUsuario.setText("");
        }catch(Exception ex)
         {
           JOptionPane.showMessageDialog(this,"Algo ha fallado");
             } 
         
    }//GEN-LAST:event_BotonTablaUsuariosActionPerformed

    private void BotonRegresoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresoMenuActionPerformed
        // Boton para regresar a la pantalla de opciones profesores
        //visorCreacionUsuario--------->visiorOpcionesProfesor
        visiorOpcionesProfesor pantalla = new visiorOpcionesProfesor();
        pantalla.setVisible(true);
         dispose();
        setVisible(false);
    }//GEN-LAST:event_BotonRegresoMenuActionPerformed

    private void tablavisualizacionUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablavisualizacionUsuariosMouseClicked
        //porcion de codigo para vizualisar en los espacios de textfield la fila seleccionada por un maus del usuario
        //Para mejor experiencia de usuario cuando seleccione una linea se visualise en los textfields para sea claro cual usuario es el que editara o eliminara
        DefaultTableModel tablon = (DefaultTableModel)tablavisualizacionUsuarios.getModel();
        
       try{//para evitar problemas usaremos un try catch
        int selectedRowIndex = tablavisualizacionUsuarios.getSelectedRow();
        //el index es RowIndex es la fila donde se presione y el numero es la guia para cual dato de x columna ira al textfield correspondiente
        verNombreUsuario.setText(tablon.getValueAt (selectedRowIndex,0).toString());
         verIdUsuario.setText(tablon.getValueAt (selectedRowIndex,1).toString() );
          verCorreoUsuario.setText(tablon.getValueAt (selectedRowIndex,2).toString() );
           verContraseñaUsuario.setText(tablon.getValueAt (selectedRowIndex,3).toString() );
           rolUsuario.setText(tablon.getValueAt (selectedRowIndex,4).toString() );
          
       }catch(Exception ex)
         {
             }
        
            
        
    }//GEN-LAST:event_tablavisualizacionUsuariosMouseClicked

    private void botonCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearUsuarioActionPerformed
        // Boton para agregar a la base de datos la linea con los datos del nuevo usuario
        //procesos para meter la informacion en la base de datos
       
        String verNombreUsuario2=verNombreUsuario.getText();
        String verIdUsuario2=verIdUsuario.getText();
        String verCorreoUsuario2=verCorreoUsuario.getText();
        String verContraseñaUsuario2=verContraseñaUsuario.getText();
        String rolUsuario2=rolUsuario.getText();
        //instacion del defaultablemodel para poder agregar a la jtabla la informacion agregada
         DefaultTableModel tablon = (DefaultTableModel)tablavisualizacionUsuarios.getModel(); 
         
         if(cadenaVisualisador==1){//Si no se ha desplegado la tabla de datos No se podra usar el boton de agregar usuario
             
         try{//Try catch para realisar los procesos de introducion de verificacion de datos e introduccion a la base de datos
        if(verNombreUsuario2.equals("")||verIdUsuario2.equals("")||verCorreoUsuario2.equals("")||verContraseñaUsuario2.equals("")||rolUsuario2.equals("")){
        //en caso de uno de los 5 espacios esta ausente no se procedera la operacion
             JOptionPane.showMessageDialog(this,"No se puede agregar a la base con espacios vacios");
        }else{//cuando todo este lleno
         ////////////////////procedimientos para meter los datos a la base de datos////
         
         /////////////////////////////////////////////////////////////////////////////
                       
        
         }
           
        }catch(Exception ex)
         {
           JOptionPane.showMessageDialog(this,"Ha fallado agregar al usuario");  
             }
         
         }//corchete del if
         
        
        //Si los datos fueron introducidos en la base de datos la variable de candado sera 1 y se mostraran en la jtabla
        //Esta medida se da para evitar una desconexion de datos en la jtable y la base de datos dandole prioridad de recibimiento primero a la base de datos.
        if (cadenaVisualisador==1){
           
         //addRow: agregar la informacion como una linea a la tabla del jframe   
         tablon.addRow(new Object[]{verNombreUsuario2,verIdUsuario2,verCorreoUsuario2,verContraseñaUsuario2,rolUsuario2});
          //luego de agregar los datos a la tabla limpiamos los textfields
         verNombreUsuario.setText("");
         verIdUsuario.setText("");
          verCorreoUsuario.setText("" );
           verContraseñaUsuario.setText("" );
           rolUsuario.setText("");
         JOptionPane.showMessageDialog(this,"Se ha agregado el usuario");
      
             }else{
            JOptionPane.showMessageDialog(this,"No se puede usar esta funcion hasta activar la tabla");
        }
        
         
    //////////////////////////////////////////////////////////////////////////////////
    }//GEN-LAST:event_botonCrearUsuarioActionPerformed

    private void botonEditarDatosUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarDatosUsuarioActionPerformed
        // Boton para editar el cambio en los datos de una linea
        int candadoEdicion=0;
        //instacion del defaultablemodel para poder hacer manipulacion en la jtabla
        DefaultTableModel tablon = (DefaultTableModel)tablavisualizacionUsuarios.getModel();
         //selectrowindex es usado para manipular que linea el usuario escoja 
        int linea = tablavisualizacionUsuarios.getSelectedRow(); 
             
        if (cadenaVisualisador==1){//Si no se ha desplegado la tabla de datos No se podra usar el boton de agregar usuario
            
        try{//para evitar problemas usaremos un try catch
             //el codigo por si solo puede "funcionar" pero genera alertas rojas por tocar una linea en la tabla, una por una
             //con un try catch evitamos la acumulacion de alertas al punto de congelar la funcion de tocar una linea
              if (linea>=0){//cualquier linea esta siendo tocada
                  
             ///Espacio para realisar los procesos de base de datos para editar la informacion/////////
             
             //////////////////////////////////////////////////////////////////////////////////////////
             
            //restablecemos los datos en la linea tocada con la inforacion que se encuentre actualmente en los textfields
             tablon.setValueAt(verNombreUsuario.getText(),linea,0);   
             tablon.setValueAt(verIdUsuario.getText(),linea,1);   
             tablon.setValueAt(verCorreoUsuario.getText(),linea,2);
             tablon.setValueAt(verContraseñaUsuario.getText(),linea,3);
             tablon.setValueAt(rolUsuario.getText(),linea,4);
           
            }//
             
            candadoEdicion=1; 
         }catch(Exception ex)
         {
             //mensaje para indicar que algo no funciono y exploto 
            JOptionPane.showMessageDialog(this,"No se ha logrado Editar correctamente al usuario");
             }////
        }///////////////////////////
        
        
         
         
         if (candadoEdicion==1){//si los procesos para editar la linea fueron hechos sin problemas se activara este
            if (linea>=0){///cualquier linea esta siendo tocada
             //restablecemos los datos en la linea tocada con la inforacion que se encuentre actualmente en los textfields  
             tablon.setValueAt(verNombreUsuario.getText(),linea,0);   
             tablon.setValueAt(verIdUsuario.getText(),linea,1);   
             tablon.setValueAt(verCorreoUsuario.getText(),linea,2);
             tablon.setValueAt(verContraseñaUsuario.getText(),linea,3);
             tablon.setValueAt(rolUsuario.getText(),linea,4);  
             verNombreUsuario.setText("");
             verIdUsuario.setText("");
             verCorreoUsuario.setText("" );
             verContraseñaUsuario.setText("" );
             rolUsuario.setText("");
             JOptionPane.showMessageDialog(this,"Se ha Editado al usuario correctamente");
         }///
         }else{
         JOptionPane.showMessageDialog(this,"No se puede usar esta funcion hasta activar la tabla");
         }/////////////////////////   
     
    }//GEN-LAST:event_botonEditarDatosUsuarioActionPerformed

    private void botonEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarUsuarioActionPerformed
        // Boton para Eliminar un usuario
        //no habra validacion de espacios vacios porque no se pueden agregar lineas con espacios "vacios" en si
        int candadoEliminacion=0;//variable para cerrar los procesos de impresion en la tabla del jframe
        //selectrowindex es usado para manipular que linea el usuario escoja 
        int selectedRowIndex = tablavisualizacionUsuarios.getSelectedRow(); 
         //instacion del defaultablemodel para poder hacer manipulacion en la jtabla
        DefaultTableModel tablon = (DefaultTableModel)tablavisualizacionUsuarios.getModel();
        
        if (cadenaVisualisador==1){//Si no se ha desplegado la tabla de datos No se podra usar el boton de Eliminacion usuario
            
        try{//para evitar problemas usaremos un try catch
             //el codigo por si solo puede "funcionar" pero genera alertas rojas por tocar una linea en la tabla, una por una
             //con un try catch evitamos la acumulacion de alertas al punto de congelar la funcion de tocar una linea
             
             ////////Espacio para realisar los procedimientos para eliminar los datos en la base de datos
             
             //////////////////////////////////////////////////////////////////////////////////////////
             
             tablon.removeRow(selectedRowIndex);//procedimiento para eliminar LA linea recien tocada de la jtabla
            candadoEliminacion=1; 
        }catch(Exception ex)
         {
             //mensaje para indicar que algo no funciono y exploto 
            JOptionPane.showMessageDialog(this,"No se ha logrado Eliminar correctamente al usuario");
             }   
        }
        
          
       
        if (candadoEliminacion==1){///If cerrado por una variable int
            //si los procesos de eliminacion de usuario fueron hechos correctamente se elimina de la jtable
            
             JOptionPane.showMessageDialog(this,"Se ha Eliminado al usuario");
             //Se limpian los espacios para nuevas operaciones despues de informar la accion,
             //en caso de presionar erroneamente Eliminar  se da la ventana de tiempo de ver los datos que borro para apuntarlos y volver a agregarlo
             verNombreUsuario.setText("");
         verIdUsuario.setText("");
          verCorreoUsuario.setText("" );
           verContraseñaUsuario.setText("" );
           rolUsuario.setText("");
        }else{
        JOptionPane.showMessageDialog(this,"No se puede usar esta funcion hasta activar la tabla");
        }
   
    }//GEN-LAST:event_botonEliminarUsuarioActionPerformed

    private void RolUsuarioProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RolUsuarioProfesorActionPerformed
        // Radio botom para elejir el rol de profesor al usuario
        if (RolUsuarioProfesor.isSelected()){
        rolUsuario.setText("Profesor");
        }
    }//GEN-LAST:event_RolUsuarioProfesorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(visorCreacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(visorCreacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(visorCreacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(visorCreacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new visorCreacionUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonRegresoMenu;
    private javax.swing.JButton BotonTablaUsuarios;
    private javax.swing.JRadioButton RolUsuarioEstudiante;
    private javax.swing.JRadioButton RolUsuarioProfesor;
    private javax.swing.JButton botonCrearUsuario;
    private javax.swing.JButton botonEditarDatosUsuario;
    private javax.swing.JButton botonEliminarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rolUsuario;
    private javax.swing.JTable tablavisualizacionUsuarios;
    private javax.swing.JTextField verContraseñaUsuario;
    private javax.swing.JTextField verCorreoUsuario;
    private javax.swing.JTextField verIdUsuario;
    private javax.swing.JTextField verNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
